-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 21:00:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema playground_magali
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema playground_magali
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `playground_magali` DEFAULT CHARACTER SET utf8 ;
USE `playground_magali` ;

-- -----------------------------------------------------
-- Table `playground_magali`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `start-date` DATE NOT NULL,
  `end-date` DATE NOT NULL,
  `quota` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `playground_magali`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `start_date` DATE NOT NULL,
  `coursesId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_units_curses_idx` (`coursesId` ASC) VISIBLE,
  CONSTRAINT `fk_units_curses`
    FOREIGN KEY (`coursesId`)
    REFERENCES `playground_magali`.`courses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `playground_magali`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titile` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `start_date` DATE NOT NULL,
  `visible` TINYINT NOT NULL,
  `unitId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lessons_units_idx` (`unitId` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_units`
    FOREIGN KEY (`unitId`)
    REFERENCES `playground_magali`.`units` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `playground_magali`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `playground_magali`.`blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`blocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  `typeId` INT NOT NULL,
  `lessonsId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blocks_types_idx` (`typeId` ASC) VISIBLE,
  INDEX `fk_blocks_lessons_idx` (`lessonsId` ASC) VISIBLE,
  CONSTRAINT `fk_blocks_lessons`
    FOREIGN KEY (`lessonsId`)
    REFERENCES `playground_magali`.`lessons` (`id`),
  CONSTRAINT `fk_blocks_types`
    FOREIGN KEY (`typeId`)
    REFERENCES `playground_magali`.`types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `playground_magali`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `playground_magali`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_categories_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_users_categories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `playground_magali`.`categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `playground_magali`.`courses_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `playground_magali`.`courses_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usersId` INT NOT NULL,
  `coursesId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_courses_idx` (`usersId` ASC) VISIBLE,
  INDEX `fk_courses_users_idx` (`coursesId` ASC) VISIBLE,
  CONSTRAINT `fk_courses_users`
    FOREIGN KEY (`coursesId`)
    REFERENCES `playground_magali`.`courses` (`id`),
  CONSTRAINT `fk_users_courses`
    FOREIGN KEY (`usersId`)
    REFERENCES `playground_magali`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
